-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.


<<<<<<< db/create.sql
CREATE TABLE Seller (
    sr_sellerkey BIGINT NOT NULL PRIMARY KEY,
    sr_userkey BIGINT NOT NULL,
    sr_registrationdate DATE NOT NULL
);

   ALTER TABLE Seller
ADD CONSTRAINT seller_user_fk
   FOREIGN KEY (sr_userkey) REFERENCES user(u_userkey);


CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);


CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);
>>>>>>> db/create.sql
