-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) UNIQUE NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    available BOOLEAN DEFAULT TRUE
);

CREATE TABLE Purchases (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL REFERENCES Users(id),
    pid INT NOT NULL REFERENCES Products(id),
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE seller (
    sr_sellerkey BIGINT NOT NULL PRIMARY KEY,
    sr_userkey BIGINT NOT NULL,
    sr_RegistrationDate DATE NOT NULL
);


CREATE TABLE inventory (
    in_sellerkey BIGINT NOT NULL,
    in_productkey BIGINT NOT NULL PRIMARY KEY,
    in_actionstatus BOOLEAN NOT NULL,
    in_discount DECIMAL(10, 2),
    in_tax DECIMAL(10, 2)
);


   ALTER TABLE seller
ADD CONSTRAINT seller_user_fk
   FOREIGN KEY (sr_userkey) REFERENCES user(u_userkey);



    ALTER TABLE inventory
ADD CONSTRAINT fk_product 
    FOREIGN KEY (in_productkey) REFERENCES product(p_productkey);
